package main

// A bot's environment is fnox's (https://fnox.jdx.dev), resolved by mise:
//
//	<dir>/fnox.toml          every variable, each held by a provider. Lasso writes
//	                         it once, with two providers — "lasso", age-encrypted
//	                         to lasso's own key (botkey.go), the default, and
//	                         "plain" — and after that only through the fnox CLI,
//	                         so a human can point default_provider at 1Password,
//	                         a vault or anything else fnox speaks.
//	<dir>/.mise/config.toml  lasso's: experimental mode and [secrets.fnox], so
//	                         `mise run bot` asks fnox for the variables the task
//	                         lists (botTaskScript) and hands them to that task
//	                         alone — never to the shell or `mise env`. The bot's
//	                         own mise.toml (tools, say) stays the human's.
//
// Values go in on STDIN, never argv (where `ps` shows them), and a secret's
// never comes back out: listings carry only what `fnox list` prints without
// --values, which for an encrypting provider is ciphertext lasso drops.

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

const botToolTimeout = 60 * time.Second

// botRun runs `<tool> <args>` (tool is mise or fnox) with dir as the working
// directory on b's host, through a login shell so the tools are on PATH the
// way they are for the human. A var so tests can record the calls.
var botRun = func(b Backend, dir, tool string, args []string, stdin []byte) ([]byte, error) {
	parts := []string{"cd", shellQuote(dir), "&&", tool}
	for _, a := range args {
		parts = append(parts, shellQuote(a))
	}
	line := strings.Join(parts, " ")
	if rb, ok := b.(*remoteBackend); ok {
		return rb.runStdin(`${SHELL:-sh} -lc `+shellQuote(line), stdin)
	}
	ctx, cancel := context.WithTimeout(context.Background(), botToolTimeout)
	defer cancel()
	shell := os.Getenv("SHELL")
	if shell == "" {
		shell = "sh"
	}
	cmd := exec.CommandContext(ctx, shell, "-lc", line)
	cmd.Stdin = bytes.NewReader(stdin)
	var errBuf bytes.Buffer
	cmd.Stderr = &errBuf
	out, err := cmd.Output()
	if err != nil {
		if msg := strings.TrimSpace(errBuf.String()); msg != "" {
			return out, fmt.Errorf("%s %s: %s", tool, strings.Join(args, " "), lastLines(msg, 3))
		}
		return out, fmt.Errorf("%s %s: %w", tool, strings.Join(args, " "), err)
	}
	return out, nil
}

// The oldest mise with task `secrets` and [secrets.fnox], and the oldest fnox
// that mise accepts for it.
const (
	botMinMise = "2026.10.4"
	botMinFnox = "1.39.0"
)

var botToolsOK sync.Map // host -> time checked

// botCheckTools refuses a host whose mise or fnox is missing or too old, with
// what to run. Remembered per host for ten minutes once it passes.
func botCheckTools(b Backend) error {
	if t, ok := botToolsOK.Load(b.Name()); ok && time.Since(t.(time.Time)) < 10*time.Minute {
		return nil
	}
	home, _ := b.HomeDir()
	for _, c := range []struct{ tool, min, fix string }{
		{"mise", botMinMise, "mise self-update"},
		{"fnox", botMinFnox, "mise use -g fnox@latest"},
	} {
		out, err := botRun(b, home, c.tool, []string{"--version"}, nil)
		if err != nil {
			return fmt.Errorf("bots need %s %s or newer on %s, and it is not installed (%s)", c.tool, c.min, b.Name(), c.fix)
		}
		v := toolVersion(string(out))
		if versionLess(v, c.min) {
			return fmt.Errorf("bots need %s %s or newer on %s, which has %s (%s)", c.tool, c.min, b.Name(), v, c.fix)
		}
	}
	botToolsOK.Store(b.Name(), time.Now())
	return nil
}

// toolVersion picks the first dotted number out of `x --version`.
func toolVersion(s string) string {
	for _, f := range strings.Fields(s) {
		if f != "" && f[0] >= '0' && f[0] <= '9' && strings.Contains(f, ".") {
			return f
		}
	}
	return ""
}

// versionLess compares dotted numeric versions; an unparseable one is less.
func versionLess(a, b string) bool {
	pa, pb := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(pb); i++ {
		if i >= len(pa) {
			return true
		}
		x, err1 := strconv.Atoi(pa[i])
		y, _ := strconv.Atoi(pb[i])
		if err1 != nil {
			return true
		}
		if x != y {
			return x < y
		}
	}
	return false
}

func botFnoxFile(dir string) string       { return filepath.Join(dir, "fnox.toml") }
func botMiseConfigFile(dir string) string { return filepath.Join(dir, ".mise", "config.toml") }

const botMiseConfig = `# Generated by lasso for this bot; lasso rewrites it on every save.
# The bot's own mise.toml, if any, is yours.
min_version = "` + botMinMise + `"

[settings]
experimental = true

# The task's variables come from fnox.toml (see .mise/tasks/bot for which).
[secrets.fnox]
`

// botEnvInit prepares the folder for `mise run bot`: lasso's mise config,
// trusted, and a fnox.toml when there is none. An existing fnox.toml is the
// human's and is left alone.
func botEnvInit(b Backend, dir string) error {
	if err := botCheckTools(b); err != nil {
		return err
	}
	cfg := botMiseConfigFile(dir)
	if err := b.MkdirAll(filepath.Dir(cfg), 0o755); err != nil {
		return err
	}
	if err := b.WriteFile(cfg, []byte(botMiseConfig), 0o644); err != nil {
		return err
	}
	if _, err := botRun(b, dir, "mise", []string{"trust", cfg}, nil); err != nil {
		return err
	}
	if _, err := b.Stat(botFnoxFile(dir)); err == nil {
		return nil
	}
	recipient, keyPath, err := botAgeRecipient(b)
	if err != nil {
		return fmt.Errorf("lasso's age key: %w", err)
	}
	return b.WriteFile(botFnoxFile(dir), []byte(botFnoxConfig(recipient, keyPath)), 0o644)
}

func botFnoxConfig(recipient, keyPath string) string {
	return fmt.Sprintf(`# This bot's environment, managed with fnox (https://fnox.jdx.dev).
# lasso adds and removes variables through the fnox CLI. Secrets go to
# default_provider: "lasso" encrypts them to lasso's own age key. To keep them
# somewhere else, add a provider (fnox provider add) and make it the default.
default_provider = "lasso"

[providers]
lasso = { type = "age", recipients = [%q], key_file = %q }
plain = { type = "plain" }
`, recipient, keyPath)
}

type botEnvVar struct {
	Key      string `json:"key"`
	Value    string `json:"value,omitempty"` // plain values only; never a secret's
	Secret   bool   `json:"secret"`
	Provider string `json:"provider,omitempty"`
}

// botEnvList lists the variables the bot's own fnox.toml defines.
func botEnvList(b Backend, dir string) ([]botEnvVar, error) {
	if _, err := b.Stat(botFnoxFile(dir)); err != nil {
		return []botEnvVar{}, nil
	}
	out, err := botRun(b, dir, "fnox", []string{"list", "--full", "--sources"}, nil)
	if err != nil {
		return nil, err
	}
	return parseFnoxList(string(out), botFnoxFile(dir)), nil
}

// parseFnoxList reads `fnox list --full --sources`: a fixed-width table whose
// header names the columns. Only rows from this folder's fnox.toml are kept
// (fnox also lists the global config's), and only a "plain" provider's
// provider key is shown, since for that provider it IS the value.
func parseFnoxList(out, file string) []botEnvVar {
	vars := []botEnvVar{}
	lines := strings.Split(out, "\n")
	hi := -1
	for i, l := range lines {
		if strings.Contains(l, "Key") && strings.Contains(l, "Source File") {
			hi = i
			break
		}
	}
	if hi < 0 {
		return vars
	}
	head := lines[hi]
	cols := []string{"Key", "Type", "Source File", "Provider Key", "Description"}
	at := make([]int, len(cols))
	for i, c := range cols {
		if at[i] = strings.Index(head, c); at[i] < 0 {
			return vars
		}
	}
	cell := func(l string, i int) string {
		start := at[i]
		if start >= len(l) {
			return ""
		}
		end := len(l)
		if i+1 < len(at) && at[i+1] < end {
			end = at[i+1]
		}
		return strings.TrimSpace(l[start:end])
	}
	for _, l := range lines[hi+1:] {
		key := cell(l, 0)
		if !botEnvKeyRE.MatchString(key) || cell(l, 2) != file {
			continue
		}
		provider := strings.TrimSuffix(strings.TrimPrefix(cell(l, 1), "provider ("), ")")
		v := botEnvVar{Key: key, Provider: provider, Secret: provider != "plain"}
		if !v.Secret {
			v.Value = cell(l, 3)
		}
		vars = append(vars, v)
	}
	return vars
}

// botEnvKeys is the variable names the task must ask mise for: every one but
// lasso's own OAuth credentials, which reach claude only through a server's
// headersHelper (the refresh token and client secret never do).
func botEnvKeys(b Backend, dir string) []string {
	vars, err := botEnvList(b, dir)
	if err != nil {
		return nil
	}
	keys := make([]string, 0, len(vars))
	for _, v := range vars {
		if !strings.HasPrefix(v.Key, botOAuthKeyPrefix) {
			keys = append(keys, v.Key)
		}
	}
	return keys
}

// botEnvSet writes one variable: a secret to fnox's default provider, a plain
// value to "plain". Both ride stdin.
func botEnvSet(b Backend, dir, key, value string, secret bool) error {
	if !botEnvKeyRE.MatchString(key) {
		return fmt.Errorf("%q is not an environment variable name", key)
	}
	if !secret && hasControl(value) {
		return fmt.Errorf("a plain value cannot contain control characters; mark it secret")
	}
	if err := botEnvInit(b, dir); err != nil {
		return err
	}
	args := []string{"set", key}
	if !secret {
		args = append(args, "--provider", "plain")
	}
	_, err := botRun(b, dir, "fnox", args, []byte(value))
	return err
}

func botEnvUnset(b Backend, dir, key string) error {
	if !botEnvKeyRE.MatchString(key) {
		return fmt.Errorf("%q is not an environment variable name", key)
	}
	_, err := botRun(b, dir, "fnox", []string{"remove", key}, nil)
	return err
}

// botLaunchTasks lists the mise tasks defined in the bot's folder that can
// launch it: the generated `bot` and any the human wrote, never `restart`.
// mise's own listing, so a task in the bot's mise.toml counts as well as a file
// in .mise/tasks/; tasks from the global config are left out.
func botLaunchTasks(b Backend, dir string) ([]string, error) {
	out, err := botRun(b, dir, "mise", []string{"tasks", "ls", "--json"}, nil)
	if err != nil {
		return nil, err
	}
	var tasks []struct {
		Name   string `json:"name"`
		Source string `json:"source"`
	}
	if err := json.Unmarshal(out, &tasks); err != nil {
		return nil, fmt.Errorf("read mise's task list: %w", err)
	}
	prefix := filepath.Clean(dir) + string(filepath.Separator)
	names := []string{}
	for _, t := range tasks {
		if t.Name == "restart" || !strings.HasPrefix(t.Source, prefix) || !botTaskRE.MatchString(t.Name) {
			continue
		}
		names = append(names, t.Name)
	}
	sort.Strings(names)
	return names, nil
}

// botCheckLaunchTask refuses a launch task the folder does not define, which
// would leave keep-running relaunching a command that fails. A folder mise
// cannot list is not refused: its task list is unknown, not empty.
func botCheckLaunchTask(b Backend, r *botRecord) error {
	if r.LaunchTask == "" {
		return nil
	}
	names, err := botLaunchTasks(b, expandTildeOn(b, r.Dir))
	if err != nil {
		return nil
	}
	for _, n := range names {
		if n == r.LaunchTask {
			return nil
		}
	}
	return fmt.Errorf("the folder has no mise task %q (it has: %s)", r.LaunchTask, strings.Join(names, ", "))
}
